### ISSUE TITLE
Error: Cant find input source with id=com.apple.keylayout.ABC

### ISSUE THREAD

**Issue by nidugin** [norflin321/fn-lang-switcher#1]
Executing the script I get an error: Error: Cant find input source with id=com.apple.keylayout.ABC
<img width="504" alt="image" src="https://user-images.githubusercontent.com/73384534/178973154-5bad3856-b3bb-4644-9e91-440b45e809df.png">

**Comment by Goodmain** [comment]
@Balemika Maybe you have a different keylayout. If you already installed issw you could check what keylayouts do you have. Type `issw -l`
```
com.apple.keylayout.ABC
com.apple.CharacterPaletteIM
com.apple.PressAndHold
com.apple.keylayout.RussianWin
```

**Comment by nidugin** [comment]
Thanks ;)

**Comment by dAverk** [comment]
@Goodmain maybe you can close this issue?

**Comment by Goodmain** [comment]
@dAverk I don't have permissions for that
